config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("eventree.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Events URLs
    path("events/", include("eventree.events.urls", namespace="events")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

eventree/events/meals/urls.py
from django.urls import path
from . import views

app_name = 'meals'

urlpatterns = [
    # Meal URLs
    path('', views.MealListView.as_view(), name='meal_list'),
    path('<int:pk>/', views.MealDetailView.as_view(), name='meal_detail'),
    
    # Meal Selection URLs
    path('select/<int:registration_id>/', views.MealSelectionView.as_view(), name='meal_selection'),
    path('selections/', views.MealSelectionListView.as_view(), name='meal_selection_list'),
    path('selections/<int:pk>/', views.MealSelectionDetailView.as_view(), name='meal_selection_detail'),
    path('selections/<int:pk>/update/', views.MealSelectionUpdateView.as_view(), name='meal_selection_update'),
    
    # API endpoints for meal availability
    path('<int:pk>/availability/', views.MealAvailabilityView.as_view(), name='meal_availability'),
]

eventree/events/urls.py
from django.urls import path, include
from . import views

app_name = 'events'

urlpatterns = [
    # Event URLs
    path('', views.EventListView.as_view(), name='event_list'),
    path('<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
    path('<int:pk>/register/', views.EventRegistrationView.as_view(), name='event_register'),
    
    # Include registration and meal URLs
    path('registrations/', include(('eventree.events.registrations.urls', 'events'), namespace='registrations')),
    path('meals/', include(('eventree.events.meals.urls', 'events'), namespace='meals')),

]

eventree/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

eventree/events/forms.py
from django import forms
from .models import Event
from .registrations.models import Registration

class EventRegistrationForm(forms.ModelForm):
    class Meta:
        model = Registration
        fields = []  # No fields needed as we'll set event and user in the view
        
    def clean(self):
        cleaned_data = super().clean()
        if hasattr(self, 'instance') and hasattr(self.instance, 'event') and self.instance.event:
            if not self.instance.event.is_available:
                raise forms.ValidationError("This event is already full.")
        return cleaned_data

eventree/events/meals/forms.py
from django import forms
from django.core.validators import MinValueValidator
from .models import MealSelection, Meal

class MealSelectionForm(forms.ModelForm):
    quantity = forms.IntegerField(
        validators=[MinValueValidator(1, message="Quantity must be at least 1")],
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'min': '1',
            'max': '10'
        })
    )

    class Meta:
        model = MealSelection
        fields = ['meal', 'quantity']
        widgets = {
            'meal': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        registration = kwargs.pop('registration', None)
        super().__init__(*args, **kwargs)
        if registration:
            # Only show meals from the event this registration is for
            self.fields['meal'].queryset = Meal.objects.filter(
                event=registration.event,
                is_active=True
            )

    def clean(self):
        cleaned_data = super().clean()
        meal = cleaned_data.get('meal')
        quantity = cleaned_data.get('quantity')

        if meal and quantity:
            if not meal.is_available():
                raise forms.ValidationError("This meal is no longer available.")
            
            if quantity > meal.remaining_quantity():
                raise forms.ValidationError(
                    f"Only {meal.remaining_quantity()} servings of this meal are available."
                )
        
        return cleaned_data

eventree/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

eventree/events/meals/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.http import Http404, JsonResponse
from .models import Meal, MealSelection
from ..models import Event
from ..registrations.models import Registration
from .forms import MealSelectionForm


class MealListView(ListView):
    model = Meal
    template_name = 'meals/meal_list.html'
    context_object_name = 'meals'

    def get_queryset(self):
        queryset = Meal.objects.all()
        if not self.request.user.is_staff:
            queryset = queryset.filter(is_active=True)
        
        event_id = self.request.GET.get('event')
        if event_id:
            queryset = queryset.filter(event_id=event_id)
            
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event_id = self.request.GET.get('event')
        if event_id:
            context['event'] = get_object_or_404(Event, pk=event_id)
        return context


class MealDetailView(DetailView):
    model = Meal
    template_name = 'meals/meal_detail.html'
    context_object_name = 'meal'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_available'] = self.object.is_available()
        context['remaining_quantity'] = self.object.remaining_quantity()
        return context


class MealSelectionView(LoginRequiredMixin, CreateView):
    model = MealSelection
    template_name = 'meals/meal_selection_form.html'
    form_class = MealSelectionForm

    def get_success_url(self):
        return reverse_lazy('events:registrations:registration_detail', 
                          kwargs={'pk': self.kwargs['registration_id']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['registration'] = get_object_or_404(
            Registration, pk=self.kwargs['registration_id']
        )
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        registration = get_object_or_404(Registration, pk=self.kwargs['registration_id'])
        kwargs['registration'] = registration
        return kwargs

    def form_valid(self, form):
        registration = get_object_or_404(
            Registration, pk=self.kwargs['registration_id']
        )
        if registration.user != self.request.user and not self.request.user.is_staff:
            messages.error(self.request, 'You can only select meals for your own registration.')
            return redirect('events:registrations:registration_detail', 
                          pk=registration.pk)
        
        form.instance.registration = registration
        try:
            response = super().form_valid(form)
            messages.success(self.request, 'Meal selection saved successfully!')
            return response
        except ValueError as e:
            messages.error(self.request, str(e))
            return self.form_invalid(form)


class MealSelectionUpdateView(LoginRequiredMixin, UpdateView):
    model = MealSelection
    template_name = 'meals/meal_selection_form.html'
    form_class = MealSelectionForm

    def get_success_url(self):
        return reverse_lazy('events:registrations:registration_detail', 
                          kwargs={'pk': self.object.registration.pk})

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.registration.user != self.request.user and not self.request.user.is_staff:
            raise Http404("Meal selection not found")
        return obj

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        registration = self.object.registration
        kwargs['registration'] = registration
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['registration'] = self.object.registration
        return context

    def form_valid(self, form):
        try:
            response = super().form_valid(form)
            messages.success(self.request, 'Meal selection updated successfully!')
            return response
        except ValueError as e:
            messages.error(self.request, str(e))
            return self.form_invalid(form)


class MealSelectionDetailView(LoginRequiredMixin, DetailView):
    model = MealSelection
    template_name = 'meals/meal_selection_detail.html'
    context_object_name = 'meal_selection'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        # Only allow staff or the user who owns the registration to view
        if not self.request.user.is_staff and obj.registration.user != self.request.user:
            raise Http404("Meal selection not found")
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['can_edit'] = (
            self.request.user.is_staff or 
            self.object.registration.user == self.request.user
        )
        return context


class MealSelectionListView(LoginRequiredMixin, ListView):
    model = MealSelection
    template_name = 'meals/meal_selection_list.html'
    context_object_name = 'meal_selections'

    def get_queryset(self):
        if self.request.user.is_staff:
            return MealSelection.objects.all()
        return MealSelection.objects.filter(
            registration__user=self.request.user
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Group meal selections by registration
        selections_by_registration = {}
        for selection in self.get_queryset():
            if selection.registration_id not in selections_by_registration:
                selections_by_registration[selection.registration_id] = {
                    'registration': selection.registration,
                    'selections': []
                }
            selections_by_registration[selection.registration_id]['selections'].append(selection)
        context['selections_by_registration'] = selections_by_registration
        return context


class MealAvailabilityView(View):
    def get(self, request, *args, **kwargs):
        meal = get_object_or_404(Meal, pk=kwargs['pk'])
        return JsonResponse({
            'is_available': meal.is_available(),
            'remaining_quantity': meal.remaining_quantity(),
            'total_capacity': meal.available_quantity,
            'meal_name': meal.name,
            'meal_type': meal.meal_type,
            'dietary_info': meal.dietary_restriction
        })

eventree/events/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Event
from .forms import EventRegistrationForm


class EventListView(ListView):
    model = Event
    template_name = 'events/event_list.html'
    context_object_name = 'events'

    def get_queryset(self):
        queryset = Event.objects.all()
        if not self.request.user.is_staff:
            queryset = queryset.filter(is_active=True)
        return queryset


class EventDetailView(DetailView):
    model = Event
    template_name = 'events/event_detail.html'
    context_object_name = 'event'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['user_registration'] = self.object.registrations.filter(
                user=self.request.user
            ).first()
        return context


class EventRegistrationView(LoginRequiredMixin, CreateView):
    template_name = 'events/registration_form.html'
    form_class = EventRegistrationForm
    success_url = reverse_lazy('events:event_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['event'] = get_object_or_404(Event, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        event = get_object_or_404(Event, pk=self.kwargs['pk'])
        if not event.is_available:
            messages.error(self.request, 'Sorry, this event is full.')
            return redirect('events:event_detail', pk=event.pk)
        
        form.instance.event = event
        form.instance.user = self.request.user
        messages.success(self.request, 'Successfully registered for the event!')
        return super().form_valid(form)

eventree/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from eventree.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user.get_absolute_url()

    def get_object(self, queryset: QuerySet | None=None) -> User:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self) -> str:
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

eventree/templates/events/event_detail.html
{% extends "base.html" %}

{% block title %}{{ event.title }}{% endblock %}

{% block content %}
<div class="container py-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'events:event_list' %}">Events</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ event.title }}</li>
    </ol>
  </nav>

  <div class="row">
    <div class="col-md-8">
      {% if event.image %}
        <img src="{{ event.image.url }}" class="img-fluid rounded mb-4" alt="{{ event.title }}">
      {% endif %}
      
      <h1 class="mb-4">{{ event.title }}</h1>
      <div class="mb-4">
        <span class="badge bg-primary me-2">{{ event.get_event_type_display }}</span>
        <span class="badge {% if event.is_available %}bg-success{% else %}bg-danger{% endif %}">
          {% if event.is_available %}Available{% else %}Full{% endif %}
        </span>
      </div>

      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">Event Details</h5>
          <p class="card-text">{{ event.description }}</p>
          <div class="row">
            <div class="col-md-6">
              <p><strong>Date:</strong> {{ event.get_event_date_string }}</p>
              <p><strong>Time:</strong> {{ event.get_event_time_string }}</p>
            </div>
            <div class="col-md-6">
              <p><strong>Location:</strong> {{ event.location }}</p>
              <p><strong>Capacity:</strong> {{ event.capacity }} guests</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title">Registration</h5>
          {% if user.is_authenticated %}
            {% if user_registration %}
              <div class="alert alert-success">
                You are registered for this event!
                <div class="mt-2">
                  <a href="{% url 'events:registrations:registration_detail' user_registration.pk %}" class="alert-link d-block mb-2">
                    View your registration
                  </a>
                  <a href="{% url 'events:meals:meal_selection' registration_id=user_registration.pk %}" class="btn btn-primary btn-sm">
                    Select Meals
                  </a>
                </div>
              </div>
            {% else %}
              {% if event.is_available %}
                <a href="{% url 'events:event_register' event.pk %}" class="btn btn-primary w-100">
                  Register Now
                </a>
              {% else %}
                <div class="alert alert-warning">
                  This event is currently full.
                </div>
              {% endif %}
            {% endif %}
          {% else %}
            <div class="alert alert-info">
              Please <a href="{% url 'account_login' %}" class="alert-link">log in</a> to register for this event.
            </div>
          {% endif %}
        </div>
      </div>

      {% if event.meals.exists %}
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Available Meals</h5>
            <div class="list-group list-group-flush">
              {% for meal in event.meals.all %}
                <div class="list-group-item {% if meal.meal_selections.all %}selected-meal bg-light border-primary{% endif %}">
                  <div class="d-flex justify-content-between align-items-start">
                    <div>
                      <h6 class="mb-1">{{ meal.name }}</h6>
                      <p class="mb-1 text-muted">{{ meal.description|truncatewords:20 }}</p>
                      {% if meal.meal_selections.all %}
                        <span class="badge bg-primary">Selected</span>
                      {% endif %}
                      <small class="text-muted d-block">
                        Available: {{ meal.remaining_quantity }} / {{ meal.available_quantity }}
                      </small>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

eventree/templates/events/event_list.html
{% extends "base.html" %}

{% block title %}Events{% endblock %}

{% block content %}
<div class="container py-5">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1>Events</h1>
    {% if user.is_staff %}
      <a href="#" class="btn btn-primary">Create Event</a>
    {% endif %}
  </div>

  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for event in events %}
      <div class="col">
        <div class="card h-100">
          {% if event.image %}
            <img src="{{ event.image.url }}" class="card-img-top" alt="{{ event.title }}">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ event.title }}</h5>
            <p class="card-text">{{ event.description|truncatewords:30 }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <small class="text-muted">{{ event.date|date:"F j, Y" }}</small>
              <span class="badge {% if event.is_available %}bg-success{% else %}bg-danger{% endif %}">
                {% if event.is_available %}Available{% else %}Full{% endif %}
              </span>
            </div>
          </div>
          <div class="card-footer bg-transparent border-top-0">
            <a href="{% url 'events:event_detail' event.pk %}" class="btn btn-outline-primary w-100">View Details</a>
          </div>
        </div>
      </div>
    {% empty %}
      <div class="col-12">
        <div class="alert alert-info" role="alert">
          No events available at this time.
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

eventree/templates/events/registration_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Register for {{ event.title }}{% endblock %}

{% block content %}
<div class="container py-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'events:event_list' %}">Events</a></li>
      <li class="breadcrumb-item"><a href="{% url 'events:event_detail' event.pk %}">{{ event.title }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Register</li>
    </ol>
  </nav>

  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title mb-4">Register for {{ event.title }}</h2>
          
          <div class="alert alert-info mb-4">
            <h5 class="alert-heading">Event Details</h5>
            <p class="mb-1"><strong>Date:</strong> {{ event.date|date:"F j, Y" }}</p>
            <p class="mb-1"><strong>Time:</strong> {{ event.date|date:"g:i A" }}</p>
            <p class="mb-1"><strong>Location:</strong> {{ event.location }}</p>
            <p class="mb-0"><strong>Available Spots:</strong> {{ event.remaining_capacity }}</p>
          </div>

          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            
            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-primary">
                Complete Registration
              </button>
              <a href="{% url 'events:event_detail' event.pk %}" class="btn btn-outline-secondary">
                Cancel
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}